SPHINX_PROJECT_NAME=Modbus TCP Component
VERSION=1v0
DOXYGEN_DIRS= ../../module_modbus_tcp/src
SOURCE_INCLUDE_DIRS= ../../module_modbus_tcp/src
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
